### ISSUE TITLE
the emb result are not displayed properly

### ISSUE THREAD

**Issue by jxlijunhao** [jwplayer/jwalk#5]
<80>^Bcjwalk.skipgram                                                                                                                       
  2 Skipgram
  3 q^A)<81>q^B}q^C(U^Dloadq^Dcgensim.utils
  4 call_on_class_only
  5 q^EU^Ktrain_countq^FK^AU^Kbatch_wordsq^GM^P'U   cbow_meanq^HK^AU^Frandomq   cnumpy.random
  6 __RandomState_ctor
  7 q
  8 )Rq^K(U^GMT19937q^Lcnumpy.core.multiarray
  9 _reconstruct
 10 q^Mcnumpy
 11 ndarray
 12 q^NK^@<85>U^Ab<87>Rq^O(K^AMp^B<85>cnumpy
 13 dtype
 14 q^PU^Bu4K^@K^A<87>Rq^Q(K^CU^A<NNNJÿÿÿÿJÿÿÿÿK^@tb<89>TÀ  ^@^@<9a>z´<9c>^H<91>Ñ±^W^W (á0lðæÀ@/=<^\Å»H<89>^E2?fj;<86><84>È£ÿ+<8f><8a><97>7À²<91    >BD½Ô<90>áÌÀ"tÑ^L^A<9f>J_ç<9a>a^Zô6&^B7P<8f>0<96>ï?^R<­`TrPI^@<8d><9f>uêqúF^F`wÄÐ^BÓu@Óû?6;ÚÃwëe~^X^ElTJ;±Ôqè^¥üÄÍ»ÊæÕ<NqÀ^_»9¾/rÞÃû<85>c<9d    ><Á<97>¸©$Oßó¤<9f><88><89>Û^A<81>÷fB^{*à<8f>Ç^C1<97><88>Ãµ
 15 ²ý¯a%ç^O¼úQ¯V|]oñ¼^@3$>^]^^<84>^V¹¢#*<9c>Æ=|â­+}y¬º<9e>¡t<91>¥£Â§<93><99>-X´ñÿ<91>Õ ^[ã<8d>Á:®9R^X^Zö5T¬Ìµwpz
 
while the deepwalks generate the result like this:
`34 10
34 -0.006326 0.201134 -0.550136 -0.086736 0.179594 -0.374418 -0.789379 0.624164 0.586701 -0.151844
1 0.094504 0.043796 -0.229939 0.156263 -0.291131 -0.483646 -0.126931 -0.573272 -0.801995 -0.569402
33 -0.355898 0.506667 0.044414 -0.187979 -0.304238 -0.409748 -0.842301 0.836314 0.630177 -0.204261
3 0.722075 0.166128 -0.633459 0.433687 0.003020 0.285339 -0.443300 0.170543 -0.330985 0.169615
 2 -0.020249 0.053541 -0.809832 0.065876 -0.453971 -0.028110 -0.347451 0.359109 -1.024664 -0.748024
4 0.104225 -0.085589 -0.371608 0.237721 -0.230345 -0.230907 -0.052962 0.588910 -1.375630 -0.303069
`
finally, the input adjmatrix  has to be put each egde in single row, waste memory

**Comment by dshore** [comment]
I understand there may be a better way to display generated results, but this comment is not actionable.  Closing this... please feel free to create a new issue that is more explicit.
